# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2

shared: &shared
  working_directory: ~/repo
  steps:
    - checkout
    # Set up the repository and fetch deps
    - run: mix local.hex --force
    - run: mix local.rebar --force
    - run: cp config/test.travis.exs config/test.exs
    - run: mix deps.get
    # Create the test database and run the tests
    - run: mix ecto.create
    - run: mix test

jobs:
  "elixir-1.4":
    <<: *shared
    docker:
      - image: circleci/elixir:1.4
      - image: circleci/postgres:9.4

workflows:
  version: 2
  build:
    jobs:
      - "elixir-1.4"
